// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEYcyoRSnOp_zZO-kdlmgdPSD9FToo24',
    appId: '1:673886652406:web:4893d93f13e287d96669d7',
    messagingSenderId: '673886652406',
    projectId: 'memory-c6816',
    authDomain: 'memory-c6816.firebaseapp.com',
    storageBucket: 'memory-c6816.firebasestorage.app',
    measurementId: 'G-0KNN8BC5RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApe2eLzfjeXGlE6Rly6txv1jJNafj5qjo',
    appId: '1:673886652406:android:dc01240a533e622d6669d7',
    messagingSenderId: '673886652406',
    projectId: 'memory-c6816',
    storageBucket: 'memory-c6816.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNnb19Zm_dqLCNctWqYz0tXGGTgLepuDU',
    appId: '1:673886652406:ios:ab3faea2128d91376669d7',
    messagingSenderId: '673886652406',
    projectId: 'memory-c6816',
    storageBucket: 'memory-c6816.firebasestorage.app',
    iosBundleId: 'com.example.memory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNnb19Zm_dqLCNctWqYz0tXGGTgLepuDU',
    appId: '1:673886652406:ios:ab3faea2128d91376669d7',
    messagingSenderId: '673886652406',
    projectId: 'memory-c6816',
    storageBucket: 'memory-c6816.firebasestorage.app',
    iosBundleId: 'com.example.memory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEYcyoRSnOp_zZO-kdlmgdPSD9FToo24',
    appId: '1:673886652406:web:c071bc4a501d44256669d7',
    messagingSenderId: '673886652406',
    projectId: 'memory-c6816',
    authDomain: 'memory-c6816.firebaseapp.com',
    storageBucket: 'memory-c6816.firebasestorage.app',
    measurementId: 'G-Q4ZJB3R220',
  );

}